-define(OPTIONS, [{detailed_constr, true}, {str_node_as_binary, true}]).

-define(DEEP_MERGED_OBJECTS, [servers, tags, components]).

-define(PROPERTY_SPEC, 
  #{'$contact' => #{<<"name">> => scalar,
                    <<"url">> => scalar,
                    <<"email">> => scalar},
    '$license' => #{<<"name">> => scalar,
                    <<"url">> => scalar},
    '$info' => #{<<"title">> => scalar,
                 <<"description">> => scalar,
                 <<"termsOfService">> => scalar,
                 <<"contact">> => '$contact',
                 <<"license">> => '$license',
                 <<"version">> => scalar},
    '$server' => #{<<"url">> => scalar,
                   <<"description">> => scalar,
                   <<"variables">> => '$serverVariables'},
    '$serverVariables' => #{'_' => '$serverVariable'},
    '$serverVariable' => #{<<"enum">> => scalar,
                           <<"default">> => scalar,
                           <<"description">> => scalar},
    '$paths' => #{'_' => '$pathItem'},
    '$pathItem' => #{<<"summary">> => scalar,
                     <<"description">> => scalar,
                     <<"get">> => '$operation',
                     <<"put">> => '$operation',
                     <<"post">> => '$operation',
                     <<"delete">> => '$operation',
                     <<"options">> => '$operation',
                     <<"head">> => '$operation',
                     <<"patch">> => '$operation',
                     <<"trace">> => '$operation',
                     <<"servers">> => '$server',
                     <<"parameters">> => '$parameter'},
    '$operation' => #{<<"tags">> => scalar,
                      <<"summary">> => scalar,
                      <<"description">> => scalar,
                      <<"externalDocs">> => '$externalDoc',
                      <<"operationId">> => scalar,
                      <<"parameters">> => '$parameter',
                      <<"requestBody">> => '$requestBody',
                      <<"responses">> => '$responses',
                      <<"callbacks">> => '$callbacks',
                      <<"deprecated">> => scalar,
                      <<"security">> => '$security',
                      <<"servers">> => '$server',
                      <<"x-handler">> => atom},
    '$security' => #{},
    '$requestBody' => #{<<"description">> => scalar,
                        <<"content">> => '$mediaTypes',
                        <<"required">> => scalar},
    '$responses' => #{<<"default">> => '$response',
                      '_' => '$response'},
    '$response' => #{<<"description">> => scalar,
                     <<"headers">> => '$headers',
                     <<"content">> => '$mediaTypes',
                     <<"links">> => '$links'},
    '$links' => #{'_' => '$link'},
    '$link' => #{<<"operationRef">> => scalar,
                 <<"operationId">> => scalar,
                 <<"parameters">> => '$map(scalar, scalar)',
                 <<"requestBody">> => scalar,
                 <<"description">> => scalar,
                 <<"server">> => '$server'},
    '$callbacks' => #{'_' => '$pathItem'},
    '$parameter' => #{<<"name">> => scalar,
                      <<"in">> => scalar,
                      <<"description">> => scalar,
                      <<"required">> => scalar,
                      <<"deprecated">> => scalar,
                      <<"allowEmptyValue">> => scalar,
                      <<"style">> => scalar,
                      <<"explode">> => scalar,
                      <<"allowReserved">> => scalar,
                      <<"schema">> => '$schema',
                      <<"example">> => scalar,
                      <<"examples">> => '$examples',
                      <<"content">> => '$mediaTypes'},
    '$examples' => #{'_' => '$example'},
    '$example' => #{<<"summary">> => scalar,
                    <<"description">> => scalar,
                    <<"value">> => scalar,
                    <<"externalValue">> => scalar},
    '$mediaTypes' => #{'_' => '$mediaType'},
    '$mediaType' => #{<<"schema">> => '$schema',
                      <<"example">> => scalar,
                      <<"examples">> => '$examples',
                      <<"encoding">> => '$encodings'},
    '$encodings' => #{'_' => '$encoding'},
    '$encoding' => #{<<"contentType">> => scalar,
                     <<"headers">> => '$headers',
                     <<"style">> => scalar,
                     <<"explode">> => scalar,
                     <<"allowReserved">> => scalar},
    '$headers' => #{'_' => '$header'},
    '$header' => #{<<"description">> => scalar,
                   <<"required">> => scalar,
                   <<"deprecated">> => scalar,
                   <<"allowEmptyValue">> => scalar,
                   <<"style">> => scalar,
                   <<"explode">> => scalar,
                   <<"allowReserved">> => scalar,
                   <<"schema">> => '$schema',
                   <<"example">> => scalar,
                   <<"examples">> => '$examples',
                   <<"content">> => '$mediaTypes'},
    '$externalDoc' => #{<<"description">> => scalar,
                        <<"url">> => scalar},
    '$components' => #{<<"schemas">> => '$schemas',
                       <<"responses">> => '$responses',
                       <<"parameters">> => '$parameters',
                       <<"examples">> => '$examples',
                       <<"requestBodies">> => '$requestBodies',
                       <<"headers">> => '$headers',
                       <<"securitySchemes">> => '$securitySchemes',
                       <<"links">> => '$links',
                       <<"callbacks">> => '$callbacks'},
    '$schemas' => #{'_' => '$schema'},
    '$schema' => #{<<"title">> => scalar,
                   <<"multipleOf">> => scalar,
                   <<"maximum">> => scalar,
                   <<"exclusiveMaximum">> => scalar,
                   <<"minimum">> => scalar,
                   <<"exclusiveMinimum">> => scalar,
                   <<"maxLength">> => scalar,
                   <<"minLength">> => scalar,
                   <<"pattern">> => scalar,
                   <<"maxItems">> => scalar,
                   <<"minItems">> => scalar,
                   <<"uniqueItems">> => scalar,
                   <<"maxProperties">> => scalar,
                   <<"minProperties">> => scalar,
                   <<"required">> => scalar,
                   <<"enum">> => scalar,
                   <<"type">> => scalar,
                   <<"allOf">> => '$schema',
                   <<"oneOf">> => '$schema',
                   <<"anyOf">> => '$schema',
                   <<"not">> => '$schema',
                   <<"items">> => '$schema',
                   <<"properties">> => '$schemas',
                   <<"additionalProperties">> => '$schema',
                   <<"description">> => scalar,
                   <<"format">> => scalar,
                   <<"default">> => scalar,
                   <<"nullable">> => scalar,
                   <<"discriminator">> => '$discriminator',
                   <<"readOnly">> => scalar,
                   <<"writeOnly">> => scalar,
                   <<"xml">> => '$xml',
                   <<"externalDocs">> => '$externalDoc',
                   <<"example">> => scalar,
                   <<"deprecated">> => scalar},
    '$discriminator' => #{<<"properyName">> => scalar,
                          <<"mapping">> => '$map(scalar, scalar)'},
    '$map(scalar, scalar)' => #{'_' => 'scalar'},
    '$xml' => #{<<"name">> => scalar,
                <<"namespace">> => scalar,
                <<"prefix">> => scalar,
                <<"attribute">> => scalar,
                <<"wrapped">> => scalar},
    '$parameters' => #{'_' => '$parameter'},
    '$requestBodies' => #{'_' => '$requestBody'},
    '$securitySchemes' => #{'_' => '$securityScheme'},
    '$securityScheme' => #{<<"type">> => scalar,
                           <<"description">> => scalar,
                           <<"name">> => scalar,
                           <<"in">> => scalar,
                           <<"scheme">> => scalar,
                           <<"bearerFormat">> => scalar,
                           <<"flows">> => '$oautFlows',
                           <<"openIdConnectUrl">> => scalar},
    '$oautFlows' => #{<<"implicit">> => '$oautFlow',
                      <<"password">> => '$oautFlow',
                      <<"clientCredentials">> => '$oautFlow',
                      <<"authorizationCode">> => '$oautFlow'},
    '$oautFlow' => #{<<"authorizationUrl">> => scalar,
                     <<"tokenUrl">> => scalar,
                     <<"refreshUrl">> => scalar,
                     <<"scopes">> => '$map(scalar, scalar)'},
    '$tag' => #{<<"name">> => scalar,
                <<"description">> => scalar,
                <<"externalDocs">> => '$externalDoc'},
    <<"openapi">> => scalar,
    <<"info">> => '$info',
    <<"servers">> => '$server',
    <<"paths">> => '$paths',
    <<"components">> => '$components',
    <<"security">> => '$security',
    <<"tags">> => '$tag',
    <<"externalDoc">> => '$externalDoc'
  }).